all:  pjass

pjass: lex.yy.c grammar.tab.c grammar.tab.h misc.o
	gcc -O2 lex.yy.c grammar.tab.c misc.c -lfl -o $@

lex.yy.c: token.l
	flex $<

grammar.tab.c: grammar.y
	bison $<

grammar.tab.h: grammar.y
	bison -d $<

clean:
	del grammar.tab.h
	del grammar.tab.c
	del lex.yy.c
	del pjass.exe

t:
	./pjass <t.txt

package:
	tar Ccvfz ../ jass2.tar.gz  jass2/Makefile jass2/grammar.y jass2/token.l jass2/misc.c jass2/misc.h jass2/readme.txt
